return {
	"nvim-treesitter/nvim-treesitter",
	branch = "main",
	opts = {
		ensure_installed = {
			"vim",
			"lua",
			"luadoc",
			"vimdoc",
			"html",
			"css",
			"javascript",
			"typescript",
			"json",
			"c",
			"cpp",
			"go",
			"python",
			"bash",
			"yaml",
			"toml",
			"markdown",
			"markdown_inline",
			"xml",
			"proto",
		},
		highlight = { enable = true, use_languagetree = true },
		indent = { enable = true },
		auto_install = true,
	},
}
